
# Denne filen definerer hvordan docker skal lage en eller fler container(e)

services:
  flask-server:
    container_name: flask-server
    build:
      dockerfile: dockerfile
    environment:
      SMTP_PASSWORD: $SMTP_PASSWORD 
    ports:
      - 5000:5000
      
