name: Build and Publish Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - main
      
      
env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_IMAGE_NAME: email-tracker
  DOCKER_HUB_REPO: email-tracker

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker image
        run: docker build -t ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_HUB_REPO }}:${{ github.run_number }} .

      - name: Publish docker image
        run: docker push ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_HUB_REPO }}:${{ github.run_number }}
